# plugin

server:
  host: localhost
  port: 8081
  verifier_url: "http://localhost:8081"
  base_config_path: /etc/vultisig
  vaults_file_path: test/vaults
  mode: plugin
  plugin:
    type: fees

database:
  dsn: postgres://myuser:mypassword@localhost:5432/vultisig-plugin?sslmode=disable

relay:
  server: https://api.vultisig.com/router

redis:
  host: localhost
  port: 6379
  password: ""
  db: 1

block_storage:
  type: s3
  endpoint: http://localhost:9000
  bucket: vultisig-plugin
  access_key: minioadmin
  secret: minioadmin
  region: us-east-1
  host: http://localhost:9000
  force_path_style: true
  disable_ssl: true

datadog:
  host: localhost
  port: 8125

vault_service:
    relay:
        server: https://api.vultisig.com/router
    local_party_prefix: "vultisig-fees-feee"

base_config_path: fee_config.json
