services:
  plugin-db: # One DB instance for all plugins, which point to different databases
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: vultisig-plugin
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "vultisig-plugin", "-U", "myuser" ]
      interval: 1s
      timeout: 5s
      retries: 3
    networks:
      - shared_network

  redis-payroll:
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - shared_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 3
    volumes:
      - redis_payroll:/data

  redis-fees:
    image: redis:latest
    ports:
      - "6377:6379"
    networks:
      - shared_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 3
    volumes:
      - redis_fees:/data

  asynqmon:
    platform: linux/amd64
    image: hibiken/asynqmon:latest
    ports:
      - "8181:8080"
    depends_on:
      - redis-payroll

  minio-plugin:
    build:
      context: .
      dockerfile: Dockerfile.minio
      platforms:
        - linux/amd64
    ports:
      - "9100:9000" # s3 api
      - "9091:9090" # console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - shared_network

  payroll-server:
    build:
      context: .
      dockerfile: Dockerfile.Payroll.server
      platforms:
        - linux/amd64
    environment:
      REDIS_HOST: redis-payroll
      REDIS_PORT: 6379
      BLOCK_STORAGE_HOST: http://minio-plugin:9000
      DATABASE_DSN: postgres://myuser:mypassword@plugin-db:5432/vultisig-payroll?sslmode=disable
    ports:
      - "8081:8080"
    depends_on:
      plugin-db:
        condition: service_healthy
      redis-payroll:
        condition: service_healthy
      minio-plugin:
        condition: service_started
    networks:
      - shared_network

  payroll-worker:
    build:
      context: .
      dockerfile: Dockerfile.Payroll.worker
      platforms:
        - linux/amd64
    environment:
      REDIS_HOST: redis-payroll
      REDIS_PORT: 6379
      BLOCK_STORAGE_HOST: http://minio-plugin:9000
      DATABASE_DSN: postgres://myuser:mypassword@plugin-db:5432/vultisig-payroll?sslmode=disable
    depends_on:
      plugin-db:
        condition: service_healthy
      redis-payroll:
        condition: service_healthy
      minio-plugin:
        condition: service_started
    networks:
      - shared_network

  payroll-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.Payroll.scheduler
      platforms:
        - linux/amd64
    environment:
      REDIS_HOST: redis-payroll
      REDIS_PORT: 6379
      BLOCK_STORAGE_HOST: http://minio-plugin:9000
      DATABASE_DSN: postgres://myuser:mypassword@plugin-db:5432/vultisig-payroll?sslmode=disable
    depends_on:
      plugin-db:
        condition: service_healthy
      redis-payroll:
        condition: service_healthy
      minio-plugin:
        condition: service_started
    networks:
      - shared_network

  fee-server:
    build:
      context: .
      dockerfile: Dockerfile.Fee.server
      platforms:
        - linux/amd64
    environment:
      REDIS_HOST: redis-fees
      REDIS_PORT: 6379
      BLOCK_STORAGE_HOST: http://minio-plugin:9000
      DATABASE_DSN: postgres://myuser:mypassword@plugin-db:5432/vultisig-fee?sslmode=disable
    ports:
      - "8082:8080"
    depends_on:
      plugin-db:
        condition: service_healthy
      redis-fees:
        condition: service_healthy
      minio-plugin:
        condition: service_started
    networks:
      - shared_network

  fee-worker:
    build:
      context: .
      dockerfile: Dockerfile.Fee.worker
      platforms:
        - linux/amd64
    environment:
      REDIS_HOST: redis-fees
      REDIS_PORT: 6379
      BLOCK_STORAGE_HOST: http://minio-plugin:9000
      DATABASE_DSN: postgres://myuser:mypassword@plugin-db:5432/vultisig-fee?sslmode=disable
    depends_on:
      plugin-db:
        condition: service_healthy
      redis-fees:
        condition: service_healthy
      minio-plugin:
        condition: service_started
    networks:
      - shared_network

volumes:
  db_data:
  minio_data:
  redis_payroll:
  redis_fees:
networks:
  shared_network:
    external: true
