services:
  fee-worker:
    build:
      context: .
      dockerfile: Dockerfile.Fee.worker.dev
    volumes:
      - ./cmd:/app/cmd
      - ./plugin:/app/plugin
      - ./internal:/app/internal
      - ./api:/app/api
      - ./storage:/app/storage
      - ./common:/app/common
      - ./pkg:/app/pkg
      - ./service:/app/service
      - ./fee.worker.example.json:/app/config.json
      - ./etc/vultisig/fee.yml:/etc/vultisig/fee.yml

  fee-server:
    build:
      context: .
      dockerfile: Dockerfile.Fee.server.dev
    volumes:
      - ./cmd:/app/cmd
      - ./plugin:/app/plugin
      - ./internal:/app/internal
      - ./api:/app/api
      - ./storage:/app/storage
      - ./common:/app/common
      - ./pkg:/app/pkg
      - ./service:/app/service
      - ./fee.server.example.json:/app/config.json
      - ./etc/vultisig/fee.yml:/etc/vultisig/fee.yml

volumes:
  db_data:
  minio_data: 
networks:
  shared_network:
    external: true